# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        blog_users:
            entity:
                class: UserBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        blog_security:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: _check_path
                login_path: blog_login
                default_target_path: blog_index
            logout:
                path: _logout
                target: blog_index
                
            remember_me:
                key:        "%secret%"
                # 365 days in seconds
                lifetime: 31536000 
                path:     /
                # Defaults to the current domain from $_SERVER
                domain:   ~ 

        #main:
            #anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    encoders:
        Common\UserBundle\Entity\User:
            algorithm: bcrypt