airblog_pages:
    resource: "@AirblogBundle/Controller/PagesController.php"
    type:     annotation
    prefix:   /
    
airblog_posts:
    resource: "@AirblogBundle/Controller/PostsController.php"
    type:     annotation
    prefix:   /

