services:
    airblog:
        class: AirblogBundle\Twig\Extension\BlogExtension
        arguments: ["@doctrine", "@security.context"]
        tag:
            - { name: twig.extension }
            
