services:
    airblog:
        class: AirblogBundle\Twig\Extension\BlogExtension
        arguments: ["@doctrine", "@security.context"]
        public: false
        tags:
            - { name: twig.extension }
            
